unit UConstantes;

interface

type
  TSGDB = (sgdbMySQL, sgdbPostgreSQL);

const
  CONFIG_INI = 'CONFIG.INI';

{$REGION 'CONFIG do SGDB'}
  SESSAO_SGDB = 'BASE';
  IDENT_SGDB = 'SGDB';
  IDENT_USUARIO = 'USUARIO';
  IDENT_SENHA = 'SENHA';
  IDENT_PORTA = 'PORTA';
  IDENT_SERVIDOR = 'SERVIDOR';
  IDENT_BANCO = 'BANCO';
{$ENDREGION}

{$REGION 'CONFIG REST SERVER'}
  PORTA_REST_SERVER = 9020;
  SERVIDOR_REST_SERVER = 'localhost';
  //...
  SESSAO_REST_SERVER = 'REST_SERVER';
  IDENT_PORTA_REST_SERVER = 'PORTA';
  IDENT_SERVIDOR_REST_SERVER = 'SERVIDOR';
{$ENDREGION}

implementation

end.

